name: "CI/CD"
on: [push]
 
jobs:
  CI:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0
 
      - name: Compile
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Atlas
        uses: actions/upload-artifact@v2
        with:
          name: AtlasBukkit
          path: AtlasBukkit/target/AtlasBukkit-*.jar
      - name:  Upload AtlasBungee
        uses: actions/upload-artifact@v2
        with:
          name: Kauri Without Detections
          path: AtlasBungee/target/AtlasBungee-*.jar
      - name: Upload AtlasVelocity
        uses: actions/upload-artifact@v2
        with:
          name: Upload AtlasVelocity
          path: AtlasVelocity/target/AtlasVelocity-*.jar

